### PR TITLE
Change formatter from yapf to black

### PR DESCRIPTION
**Pull request by kitagry**
yapf doesn't support python 3.10 syntax. So, I want to change formatter from yapf to black.

### CODE REVIEW

**Review by hirosassa — APPROVED** [review]
Thanks!
I think Black is a good choice of formatter, and I also think we should report yapf to follow the Python 3.10 syntax, too.
My recommendation is to report (I mean raise a issue) for this problem to yapf repo.
What do you think?

**Comment by kitagry** [comment]
The issue is already reported. e.x) https://github.com/google/yapf/issues/1045

**Review by yokomotod — APPROVED** [review]
LGTM!

Great first step to switching formatter in the whole.

**Comment by hirosassa** [comment]
merged! thanks!

**Pull request merged**
