### PR TITLE
Publish with OIDC

### PR DESCRIPTION
**Pull request by kitagry**
I think we should use OIDC instead of username and password

https://docs.github.com/en/actions/deployment/security-hardening-your-deployments/about-security-hardening-with-openid-connect

### CODE REVIEW

**Review by yokomotod — COMMENTED** [review]
@kitagry super cool.

[question]

Don't we need any extra setting changes outside source code?

**Review by hirosassa — APPROVED** [review]
Thanks! Looks great! Please remove pypi token in the secret in this repo.

**Comment by kitagry** [comment]
> Don't we need any extra setting changes outside source code?

I set PyPI setting.

**Review by yokomotod — APPROVED** [review]

**Comment by yokomotod** [comment]
sorry i didn't approve 🙇

**Pull request merged**
